### ISSUE TITLE
Relying on `target` directory

### ISSUE THREAD

**Issue by kpiwko** [arquillian/arquillian-governor#2]
Tests will fail if `target` directory is not present. This breaks functionality when invoked via Gradle.

The value should not be hardcoded but flexible. Directory should be created if it does not exist.

**Comment by smiklosovic** [comment]
it is not a bug per se.

The file where report will be written consists of two properties.

The first one is called `file` and it defaults to this (1). The second one is called `rootDir` and it by default set to `target`.

The final path of the file is then the concatenation of these two: new File(rootDir, file).

If the gradle build fails because it fails to find `target`, just set `rootDir` in arquillian.xml to the value which signifies the already existing directory.

The creation of the directory when it does not exist was done for plain asciidoc file (3), however I am wondering why it is not created automatically when this functionality is already there (3)

(1) https://github.com/arquillian/arquillian-recorder/blob/master/arquillian-recorder-reporter/arquillian-recorder-reporter-api/src/main/java/org/arquillian/recorder/reporter/ReporterConfiguration.java#L52
(2) https://github.com/arquillian/arquillian-governor/commit/c53fb0b74b05f7dc20c5fe06ffdb40fa33892310
(3) https://github.com/arquillian/arquillian-recorder/blob/master/arquillian-recorder-reporter/arquillian-recorder-reporter-api/src/main/java/org/arquillian/recorder/reporter/ReporterConfiguration.java#L234-L253
