### ISSUE TITLE
Add support for Jira annotation on the class level.

### ISSUE THREAD

**Issue by bouskaJ** [arquillian/arquillian-governor#23]
It would be great to use Jira annotation on whole class because when I have tests for some component and this component does not work at all I have to add Jira annotation to every test method. It is very annoying.

**Comment by smiklosovic** [comment]
Currently methods are scanned before tests on any governor annotations and put into register so when  some test method is being executed, its execution is resolved against that register.

Arquillian can not skip whole test classes, skipping is done only on method level so even I scan that class, it would try to run these methods but they would be evenutally skipped because test class it belongs to is marked for skipping as such - and this would hold for every method in that class.

However I am not sure what should be done about automatic Jira issue resolving / closing. This bring additional complexity to it because I would close that Jira only on case all methods have passed. While I do not say it is not possible to do, it is just more cumbersome to get right.

**Comment by smiklosovic** [comment]
As a workaround, just annotate that class with `@Ignore` maybe? :)

**Comment by basovnik** [comment]
Annotation `@Ignore` is not suitable for this use case. 

What about to check for every test case if it contains `@Jira` annotation and if not then use class level `@Jira` annotation? The behaviour would not change. It would be just let's say a syntactic sugar...

When you have two test cases with the same `@Jira` annotation, does the governor check if both passed before it closes the issue?

**Comment by smiklosovic** [comment]
to answer you last question: no it does not check both of them.

While I understand your ideas, these are looking quite "easy" but the underlying logic would need to be rewritten. I do not have time for this project anymore. You are totally welcome to add whatever functionality you want and I will gladly review it and merge it.

@basovnik this holds for other issue you had and I did not finish.
